services:
  pfas_fastapi:
    container_name: pfas_fastapi
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1

  pfas_flask:
    container_name: pfas_flask
    build: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    environment:
      - FLASK_ENV=development
      - FASTAPI_BASE_URL=http://pfas_fastapi:8000
    depends_on:
      - pfas_fastapi
